### ISSUE TITLE
dnsdump list issue

### ISSUE THREAD

**Issue by sabatmonk** [CybernetiX-S3C/Squirt#1]
whenever i try to run, i get
`Traceback (most recent call last):
  File "squirt.py", line 250, in <module>
    dnsdump(domain)
  File "squirt.py", line 182, in dnsdump
    for entry in res['dns_records']['dns']:
TypeError: list indices must be integers, not str`

**Comment by CybernetiX-S3C** [comment]
Yes. I have noticed this 2 months ago. I have been still working on fixing the error. Thank you.

**Comment by CybernetiX-S3C** [comment]
Fixed. It works with the websites and non DNS related IP addresses.
